# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Prepare
      - name: prepare before build
        run: |
          sudo apt-get install -qy make apt-transport-https ca-certificates software-properties-common gawk jq parallel curl language-pack-fr
          uname -a
      - name: install docker-ce before build
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get -qy update
          sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
          type -a docker-compose && docker-compose version
          docker version
          docker info
      # Build
      - name: build and tests
        run: |
          ci/run-test.sh
